### ISSUE TITLE
Set to Subset matching?

### ISSUE THREAD

**Issue by antithing** [OpenGP/sparseicp#5]
Hi, and thank you for making this code available! I have a large pointcloud ( a room scan) and a smaller one (a section of the same room, sharing some, but not all points). Looking into ICP, it seems to expect two clouds of the same size ( Set to Set). Will your approach be suitable for matching these different sized clouds? I need translation and rotation to a high degree of accuracy, in real time. (<30ms)

Thanks again!

**Comment by ataiya** [comment]
I don't want to sound rude, but I am afraid you do not have a full understanding of how ICP works.
The two inputs are not expected to be of the same size.
