### ISSUE TITLE
Using not coherently oriented normals in SICP::point_to_plane

### ISSUE THREAD

**Issue by AlekseyMuraviev** [OpenGP/sparseicp#6]
I'm trying to use `SICP::point_to_plane(modelPoints, scenePoints, sceneNormals)` to match a triangular mesh and a point cloud (scenePoints). Previously, I'm calculating the normals for a point cloud (sceneNormals). From the mesh I take only vertices (modelPoints).

As a result, the data only differs even more. I assume that this is due to the arbitrary orientation of the normals of the point cloud.

What needs to be fixed in the code so that the direction of the normals does not matter? Is it possible at all?

PS Of course I can use a mesh as a scene - `SICP::point_to_plane(scenePoints, modelPoints, modelNormals).` Normals in this case will have one direction. But the number of points in the scene can be much larger than the points of the model, so it is not advisable to use this option in terms of speed.

**Comment by ataiya** [comment]
Normals orientation has no effect at all in the optimization (absolute value of point-to-plane residual before it's fed through the robust function)
